// Generated by @mdxe/fumadocs - DO NOT EDIT
import {
  defineConfig,
  defineDocs,
  frontmatterSchema,
  metaSchema,
} from 'fumadocs-mdx/config';

export const docs = defineDocs({
  // Point to parent directory (the docs content is one level up from .fumadocs)
  dir: '..',
  docs: {
    schema: frontmatterSchema,
    postprocess: {
      includeProcessedMarkdown: true,
    },
  },
  meta: {
    schema: metaSchema,
  },
});

export default defineConfig({
  mdxOptions: {
    // Add any remark/rehype plugins here
  },
});
