// Generated by @mdxe/fumadocs - DO NOT EDIT
import { resolve } from 'node:path'
import nodeLoaderCloudflare from '@hiogawa/node-loader-cloudflare/vite'
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import mdx from 'fumadocs-mdx/vite'
import { defineConfig } from 'waku/config'
import * as MdxConfig from './source.config'

export default defineConfig({
  vite: {
    plugins: [
      tailwindcss(),
      react(),
      mdx(MdxConfig),
      nodeLoaderCloudflare({
        environments: ['rsc'],
        build: true,
        getPlatformProxyOptions: {
          persist: {
            path: '.wrangler/state/v3',
          },
        },
      }),
    ],
    resolve: {
      alias: {
        '@': resolve(import.meta.dirname, 'src'),
        '@/.source': resolve(import.meta.dirname, '.source'),
      },
    },
  },
})
