/**
 * @mdxe/hono Fumadocs CSS
 *
 * CSS styles for fumadocs-style documentation layout
 *
 * @packageDocumentation
 */

/**
 * Generate fumadocs CSS with optional color customization
 */
export function generateFumadocsCSS(options: {
  color?: string
  mode?: 'light' | 'dark' | 'auto'
} = {}): string {
  const { color = 'indigo', mode = 'auto' } = options

  return `
/* Fumadocs Layout CSS - Generated by @mdxe/hono */

/* === CSS Variables === */
:root {
  /* Colors */
  --fd-background: #ffffff;
  --fd-foreground: #0f172a;
  --fd-muted: #f1f5f9;
  --fd-muted-fg: #64748b;
  --fd-border: #e2e8f0;
  --fd-primary: #6366f1;
  --fd-primary-fg: #ffffff;
  --fd-accent: #f1f5f9;
  --fd-accent-fg: #0f172a;

  /* Spacing */
  --fd-sidebar-width: 280px;
  --fd-toc-width: 220px;
  --fd-header-height: 60px;
  --fd-content-max: 860px;

  /* Typography */
  --fd-font-sans: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  --fd-font-mono: ui-monospace, SFMono-Regular, Menlo, Monaco, 'Cascadia Code', monospace;

  /* Radius */
  --fd-radius: 0.5rem;
  --fd-radius-sm: 0.25rem;
}

/* Dark mode */
@media (prefers-color-scheme: dark) {
  :root {
    --fd-background: #0f172a;
    --fd-foreground: #f1f5f9;
    --fd-muted: #1e293b;
    --fd-muted-fg: #94a3b8;
    --fd-border: #334155;
    --fd-primary: #818cf8;
    --fd-accent: #1e293b;
    --fd-accent-fg: #f1f5f9;
  }
}

[data-theme="dark"] {
  --fd-background: #0f172a;
  --fd-foreground: #f1f5f9;
  --fd-muted: #1e293b;
  --fd-muted-fg: #94a3b8;
  --fd-border: #334155;
  --fd-primary: #818cf8;
  --fd-accent: #1e293b;
  --fd-accent-fg: #f1f5f9;
}

/* === Base Reset === */
*, *::before, *::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html {
  font-family: var(--fd-font-sans);
  font-size: 16px;
  line-height: 1.6;
  background: var(--fd-background);
  color: var(--fd-foreground);
  scroll-behavior: smooth;
  scroll-padding-top: calc(var(--fd-header-height) + 1rem);
}

body {
  min-height: 100vh;
}

a {
  color: var(--fd-primary);
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

/* === Header (Navbar) === */
.fd-header {
  position: sticky;
  top: 0;
  z-index: 50;
  height: var(--fd-header-height);
  background: var(--fd-background);
  border-bottom: 1px solid var(--fd-border);
  backdrop-filter: blur(8px);
}

.fd-nav {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 100%;
  max-width: 1400px;
  margin: 0 auto;
  padding: 0 1.5rem;
}

.fd-logo {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  color: var(--fd-foreground);
  font-weight: 600;
  font-size: 1.125rem;
}

.fd-logo:hover {
  text-decoration: none;
}

.fd-logo img {
  height: 28px;
  width: auto;
}

.fd-nav-links {
  display: flex;
  align-items: center;
  gap: 1.5rem;
}

.fd-nav-links a {
  color: var(--fd-muted-fg);
  font-size: 0.875rem;
  font-weight: 500;
}

.fd-nav-links a:hover {
  color: var(--fd-foreground);
  text-decoration: none;
}

.fd-nav-actions {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.fd-search-trigger {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 0.75rem;
  background: var(--fd-muted);
  border: 1px solid var(--fd-border);
  border-radius: var(--fd-radius);
  color: var(--fd-muted-fg);
  font-size: 0.875rem;
  cursor: pointer;
  min-width: 200px;
}

.fd-search-trigger:hover {
  border-color: var(--fd-primary);
}

.fd-search-trigger kbd {
  margin-left: auto;
  padding: 0.125rem 0.375rem;
  background: var(--fd-background);
  border: 1px solid var(--fd-border);
  border-radius: var(--fd-radius-sm);
  font-size: 0.75rem;
  font-family: var(--fd-font-sans);
}

.fd-theme-toggle,
.fd-github {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 36px;
  height: 36px;
  background: transparent;
  border: 1px solid var(--fd-border);
  border-radius: var(--fd-radius);
  color: var(--fd-muted-fg);
  cursor: pointer;
}

.fd-theme-toggle:hover,
.fd-github:hover {
  background: var(--fd-muted);
  color: var(--fd-foreground);
  text-decoration: none;
}

/* === Main Container (Grid Layout) === */
.fd-container {
  display: grid;
  grid-template-columns: var(--fd-sidebar-width) 1fr var(--fd-toc-width);
  grid-template-areas: "sidebar main toc";
  max-width: 1400px;
  margin: 0 auto;
  min-height: calc(100vh - var(--fd-header-height));
}

/* === Sidebar === */
.fd-sidebar {
  grid-area: sidebar;
  position: sticky;
  top: var(--fd-header-height);
  height: calc(100vh - var(--fd-header-height));
  overflow-y: auto;
  padding: 1.5rem 1rem;
  border-right: 1px solid var(--fd-border);
  background: var(--fd-background);
}

.fd-sidebar-nav {
  font-size: 0.875rem;
}

.fd-sidebar-list {
  list-style: none;
}

.fd-sidebar-item {
  margin: 0.125rem 0;
}

.fd-sidebar-link {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 0.75rem;
  color: var(--fd-muted-fg);
  border-radius: var(--fd-radius);
  transition: background 0.15s, color 0.15s;
}

.fd-sidebar-link:hover {
  background: var(--fd-accent);
  color: var(--fd-accent-fg);
  text-decoration: none;
}

.fd-sidebar-link.active {
  background: var(--fd-primary);
  color: var(--fd-primary-fg);
  font-weight: 500;
}

.fd-sidebar-group {
  margin-top: 1rem;
}

.fd-sidebar-group:first-child {
  margin-top: 0;
}

.fd-sidebar-group-toggle {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  width: 100%;
  padding: 0.5rem 0.75rem;
  background: none;
  border: none;
  color: var(--fd-foreground);
  font-size: 0.75rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  cursor: pointer;
}

.fd-sidebar-group-toggle .icon {
  margin-left: auto;
  transition: transform 0.2s;
}

.fd-sidebar-group.open .fd-sidebar-group-toggle .icon {
  transform: rotate(90deg);
}

.fd-sidebar-items {
  list-style: none;
  padding-left: 0.75rem;
}

/* === Main Content === */
.fd-main {
  grid-area: main;
  min-width: 0;
  padding: 2rem;
}

/* === Breadcrumbs === */
.fd-breadcrumbs {
  margin-bottom: 1.5rem;
}

.fd-breadcrumbs-list {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  list-style: none;
  font-size: 0.875rem;
}

.fd-breadcrumbs-item {
  display: flex;
  align-items: center;
}

.fd-breadcrumbs-item a {
  color: var(--fd-muted-fg);
}

.fd-breadcrumbs-item a:hover {
  color: var(--fd-foreground);
}

.fd-breadcrumbs-sep {
  margin: 0 0.5rem;
  color: var(--fd-border);
}

.fd-breadcrumbs-item span[aria-current] {
  color: var(--fd-foreground);
}

/* === Article === */
.fd-article {
  max-width: var(--fd-content-max);
}

.fd-article-header {
  margin-bottom: 2rem;
  padding-bottom: 1.5rem;
  border-bottom: 1px solid var(--fd-border);
}

.fd-article-title {
  font-size: 2.25rem;
  font-weight: 700;
  line-height: 1.2;
  margin-bottom: 0.75rem;
}

.fd-article-description {
  font-size: 1.125rem;
  color: var(--fd-muted-fg);
  margin: 0;
}

/* === Article Content (Prose) === */
.fd-article-content {
  line-height: 1.75;
}

.fd-article-content h2 {
  font-size: 1.5rem;
  font-weight: 600;
  margin: 2rem 0 1rem;
  padding-top: 1.5rem;
  border-top: 1px solid var(--fd-border);
}

.fd-article-content h3 {
  font-size: 1.25rem;
  font-weight: 600;
  margin: 1.5rem 0 0.75rem;
}

.fd-article-content h4 {
  font-size: 1rem;
  font-weight: 600;
  margin: 1.25rem 0 0.5rem;
}

.fd-article-content p {
  margin: 1rem 0;
}

.fd-article-content ul,
.fd-article-content ol {
  margin: 1rem 0;
  padding-left: 1.5rem;
}

.fd-article-content li {
  margin: 0.5rem 0;
}

.fd-article-content pre {
  margin: 1.5rem 0;
  padding: 1rem;
  background: var(--fd-muted);
  border: 1px solid var(--fd-border);
  border-radius: var(--fd-radius);
  overflow-x: auto;
}

.fd-article-content code {
  font-family: var(--fd-font-mono);
  font-size: 0.875em;
}

.fd-article-content :not(pre) > code {
  padding: 0.125rem 0.375rem;
  background: var(--fd-muted);
  border-radius: var(--fd-radius-sm);
}

.fd-article-content blockquote {
  margin: 1.5rem 0;
  padding: 0.5rem 0 0.5rem 1.5rem;
  border-left: 4px solid var(--fd-primary);
  color: var(--fd-muted-fg);
  background: var(--fd-muted);
  border-radius: 0 var(--fd-radius) var(--fd-radius) 0;
}

.fd-article-content table {
  width: 100%;
  margin: 1.5rem 0;
  border-collapse: collapse;
}

.fd-article-content th,
.fd-article-content td {
  padding: 0.75rem;
  border: 1px solid var(--fd-border);
  text-align: left;
}

.fd-article-content th {
  background: var(--fd-muted);
  font-weight: 600;
}

.fd-article-content img {
  max-width: 100%;
  height: auto;
  border-radius: var(--fd-radius);
}

.fd-article-content hr {
  margin: 2rem 0;
  border: none;
  border-top: 1px solid var(--fd-border);
}

.fd-article-content a {
  color: var(--fd-primary);
  text-decoration: underline;
  text-underline-offset: 2px;
}

/* === Page Navigation (Prev/Next) === */
.fd-page-nav {
  display: flex;
  justify-content: space-between;
  gap: 1rem;
  margin-top: 3rem;
  padding-top: 2rem;
  border-top: 1px solid var(--fd-border);
}

.fd-page-nav-link {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
  padding: 0.75rem 1rem;
  background: var(--fd-background);
  border: 1px solid var(--fd-border);
  border-radius: var(--fd-radius);
  text-decoration: none;
  transition: border-color 0.15s, background 0.15s;
  max-width: 45%;
}

.fd-page-nav-link:hover {
  background: var(--fd-muted);
  border-color: var(--fd-primary);
  text-decoration: none;
}

.fd-page-nav-next {
  text-align: right;
  margin-left: auto;
}

.fd-page-nav-link small {
  font-size: 0.75rem;
  color: var(--fd-muted-fg);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.fd-page-nav-link span {
  font-size: 0.875rem;
  font-weight: 500;
  color: var(--fd-foreground);
}

/* === Table of Contents (Right Sidebar) === */
.fd-toc {
  grid-area: toc;
  position: sticky;
  top: var(--fd-header-height);
  height: calc(100vh - var(--fd-header-height));
  overflow-y: auto;
  padding: 1.5rem 1rem;
  border-left: 1px solid var(--fd-border);
}

.fd-toc-nav {
  font-size: 0.8125rem;
}

.fd-toc-title {
  display: block;
  font-size: 0.75rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--fd-muted-fg);
  margin-bottom: 1rem;
}

.fd-toc-list {
  list-style: none;
  border-left: 1px solid var(--fd-border);
}

.fd-toc-item {
  margin: 0;
}

.fd-toc-link {
  display: block;
  padding: 0.375rem 0 0.375rem 1rem;
  color: var(--fd-muted-fg);
  border-left: 2px solid transparent;
  margin-left: -1px;
  transition: color 0.15s, border-color 0.15s;
}

.fd-toc-link:hover {
  color: var(--fd-foreground);
  text-decoration: none;
}

.fd-toc-link.active {
  color: var(--fd-primary);
  border-left-color: var(--fd-primary);
}

.fd-toc-depth-3 .fd-toc-link {
  padding-left: 1.5rem;
}

.fd-toc-depth-4 .fd-toc-link {
  padding-left: 2rem;
}

.fd-toc-items {
  list-style: none;
}

/* === Responsive: Hide TOC on Medium Screens === */
@media (max-width: 1280px) {
  .fd-container {
    grid-template-columns: var(--fd-sidebar-width) 1fr;
    grid-template-areas: "sidebar main";
  }

  .fd-toc {
    display: none;
  }
}

/* === Responsive: Collapse Sidebar on Small Screens === */
@media (max-width: 768px) {
  .fd-container {
    grid-template-columns: 1fr;
    grid-template-areas: "main";
  }

  .fd-sidebar {
    display: none;
  }

  .fd-main {
    padding: 1.5rem;
  }

  .fd-article-title {
    font-size: 1.75rem;
  }

  .fd-nav-links {
    display: none;
  }

  .fd-search-trigger {
    min-width: auto;
    padding: 0.5rem;
  }

  .fd-search-trigger span,
  .fd-search-trigger kbd {
    display: none;
  }
}

/* === Utility Classes === */
.icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 1em;
  height: 1em;
}

/* === Print Styles === */
@media print {
  .fd-header,
  .fd-sidebar,
  .fd-toc,
  .fd-page-nav {
    display: none;
  }

  .fd-container {
    display: block;
  }

  .fd-main {
    padding: 0;
  }
}
`
}

/**
 * Generate client-side JS for fumadocs interactivity
 */
export function generateFumadocsJS(): string {
  return `
/* Fumadocs Client JS - Generated by @mdxe/hono */

(function() {
  'use strict';

  // Theme toggle
  const themeToggle = document.querySelector('.fd-theme-toggle');
  if (themeToggle) {
    const setTheme = (theme) => {
      document.documentElement.setAttribute('data-theme', theme);
      localStorage.setItem('fd-theme', theme);
    };

    const getPreferredTheme = () => {
      const stored = localStorage.getItem('fd-theme');
      if (stored) return stored;
      return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
    };

    // Set initial theme
    setTheme(getPreferredTheme());

    themeToggle.addEventListener('click', () => {
      const current = document.documentElement.getAttribute('data-theme');
      setTheme(current === 'dark' ? 'light' : 'dark');
    });
  }

  // Sidebar group toggle
  document.querySelectorAll('.fd-sidebar-group-toggle').forEach(toggle => {
    toggle.addEventListener('click', () => {
      const group = toggle.closest('.fd-sidebar-group');
      if (group) {
        group.classList.toggle('open');
      }
    });
  });

  // TOC active state tracking
  const tocLinks = document.querySelectorAll('.fd-toc-link');
  const headings = document.querySelectorAll('.fd-article-content h2, .fd-article-content h3, .fd-article-content h4');

  if (tocLinks.length > 0 && headings.length > 0) {
    const observerOptions = {
      rootMargin: '-100px 0px -66%',
      threshold: 0
    };

    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          const id = entry.target.getAttribute('id');
          tocLinks.forEach(link => {
            link.classList.toggle('active', link.getAttribute('href') === '#' + id);
          });
        }
      });
    }, observerOptions);

    headings.forEach(heading => {
      if (heading.id) {
        observer.observe(heading);
      }
    });
  }

  // Search trigger (placeholder - implement with algolia/orama/etc)
  const searchTrigger = document.querySelector('.fd-search-trigger');
  if (searchTrigger) {
    searchTrigger.addEventListener('click', () => {
      // TODO: Open search modal
      console.log('Search triggered');
    });

    // Keyboard shortcut: Cmd+K or Ctrl+K
    document.addEventListener('keydown', (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault();
        searchTrigger.click();
      }
    });
  }

  // Copy code button for pre blocks
  document.querySelectorAll('.fd-article-content pre').forEach(pre => {
    const button = document.createElement('button');
    button.className = 'fd-copy-button';
    button.textContent = 'Copy';
    button.addEventListener('click', async () => {
      const code = pre.querySelector('code');
      if (code) {
        await navigator.clipboard.writeText(code.textContent || '');
        button.textContent = 'Copied!';
        setTimeout(() => { button.textContent = 'Copy'; }, 2000);
      }
    });
    pre.style.position = 'relative';
    pre.appendChild(button);
  });
})();
`
}

/**
 * Additional CSS for copy button
 */
export const copyButtonCSS = `
.fd-copy-button {
  position: absolute;
  top: 0.5rem;
  right: 0.5rem;
  padding: 0.25rem 0.5rem;
  font-size: 0.75rem;
  background: var(--fd-background);
  border: 1px solid var(--fd-border);
  border-radius: var(--fd-radius-sm);
  color: var(--fd-muted-fg);
  cursor: pointer;
  opacity: 0;
  transition: opacity 0.15s;
}

pre:hover .fd-copy-button {
  opacity: 1;
}

.fd-copy-button:hover {
  background: var(--fd-muted);
  color: var(--fd-foreground);
}
`
