/**
 * Template for app/layout.tsx
 *
 * Root layout with Fumadocs provider.
 */

export interface AppLayoutOptions {
  title: string
  description?: string
  customizationDir?: string
}

export function generateAppLayout(options: AppLayoutOptions): string {
  return `// Generated by @mdxe/fumadocs - DO NOT EDIT
import './global.css';
import { RootProvider } from 'fumadocs-ui/provider';
import type { Metadata } from 'next';
import type { ReactNode } from 'react';

export const metadata: Metadata = {
  title: {
    template: '%s | ${options.title}',
    default: '${options.title}',
  },
  description: '${options.description || ''}',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
`
}
