/**
 * Template for app/(docs)/layout.tsx
 *
 * Docs layout with sidebar navigation.
 */

export interface DocsLayoutOptions {
  title: string
  githubUrl?: string
  logo?: string
  customizationDir?: string
}

export function generateDocsLayout(options: DocsLayoutOptions): string {
  const logoImport = options.logo
    ? `import Logo from '${options.customizationDir || '@customization'}/logo';`
    : ''

  const navTitle = options.logo
    ? `<Logo />`
    : `'${options.title}'`

  return `// Generated by @mdxe/fumadocs - DO NOT EDIT
import { source } from '@/lib/source';
import { DocsLayout } from 'fumadocs-ui/layouts/docs';
import type { ReactNode } from 'react';
${logoImport}

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <DocsLayout
      tree={source.pageTree}
      nav={{
        title: ${navTitle},
        ${options.githubUrl ? `githubUrl: '${options.githubUrl}',` : ''}
      }}
    >
      {children}
    </DocsLayout>
  );
}
`
}
