/**
 * Template for app/global.css
 *
 * Tailwind and Fumadocs styles.
 */

export function generateGlobalCss(): string {
  return `/* Generated by @mdxe/fumadocs - DO NOT EDIT */
@import 'tailwindcss';
@import 'fumadocs-ui/css/neutral.css';
@import 'fumadocs-ui/css/preset.css';
`
}
