/**
 * Template for next.config.mjs
 *
 * This config lives in node_modules and imports content from the user's project.
 */

export interface NextConfigOptions {
  contentDir: string
  customizationDir?: string
}

export function generateNextConfig(options: NextConfigOptions): string {
  return `// Generated by @mdxe/fumadocs - DO NOT EDIT
import { createMDX } from 'fumadocs-mdx/next';

let initOpenNext;
try {
  const mod = await import('@opennextjs/cloudflare');
  initOpenNext = mod.initOpenNextCloudflareForDev;
} catch {
  // OpenNext not installed, skip
}

if (initOpenNext) {
  initOpenNext();
}

const withMDX = createMDX();

/** @type {import('next').NextConfig} */
const config = {
  reactStrictMode: true,
  // Allow importing from the content directory outside node_modules
  transpilePackages: [],
  experimental: {
    // Enable external dir support
    externalDir: true,
  },
  // Webpack config to resolve content from user's project
  webpack: (config, { isServer }) => {
    config.resolve.alias = {
      ...config.resolve.alias,
      '@content': '${options.contentDir}',
      '@customization': '${options.customizationDir || options.contentDir + '/.mdx'}',
    };
    return config;
  },
};

export default withMDX(config);
`
}
