/**
 * Template for open-next.config.ts
 *
 * OpenNext configuration for Cloudflare Workers deployment.
 */

export function generateOpenNextConfig(): string {
  return `// Generated by @mdxe/fumadocs - DO NOT EDIT
import { defineCloudflareConfig } from "@opennextjs/cloudflare";

export default defineCloudflareConfig({});
`
}
