/**
 * Template for postcss.config.mjs
 *
 * PostCSS configuration for Tailwind CSS v4.
 */

export function generatePostcssConfig(): string {
  return `// Generated by @mdxe/fumadocs - DO NOT EDIT
export default {
  plugins: {
    '@tailwindcss/postcss': {},
  },
};
`
}
