/**
 * Template for source.config.ts
 *
 * Fumadocs MDX configuration pointing to user's content directory.
 */

export interface SourceConfigOptions {
  contentDir: string
}

export function generateSourceConfig(options: SourceConfigOptions): string {
  return `// Generated by @mdxe/fumadocs - DO NOT EDIT
import {
  defineConfig,
  defineDocs,
  frontmatterSchema,
  metaSchema,
} from 'fumadocs-mdx/config';

export const docs = defineDocs({
  // Point to user's content directory
  dir: '${options.contentDir}',
  docs: {
    schema: frontmatterSchema,
    postprocess: {
      includeProcessedMarkdown: true,
    },
  },
  meta: {
    schema: metaSchema,
  },
});

export default defineConfig({
  mdxOptions: {
    // Add any remark/rehype plugins here
  },
});
`
}
