/**
 * Template for wrangler.jsonc
 *
 * Cloudflare Workers deployment configuration.
 */

export interface WranglerConfigOptions {
  projectName: string
  domain?: string
}

export function generateWranglerConfig(options: WranglerConfigOptions): string {
  const routeConfig = options.domain
    ? `
  "routes": [
    {
      "pattern": "${options.domain}/*",
      "zone_name": "${options.domain}"
    }
  ],`
    : ''

  return `{
  // Generated by @mdxe/fumadocs - DO NOT EDIT
  "main": ".open-next/worker.js",
  "name": "${options.projectName.toLowerCase().replace(/[^a-z0-9-]/g, '-')}",
  "compatibility_date": "${new Date().toISOString().split('T')[0]}",
  "compatibility_flags": ["nodejs_compat", "global_fetch_strictly_public"],${routeConfig}
  "assets": {
    "directory": ".open-next/assets",
    "binding": "ASSETS"
  }
}
`
}
