/**
 * Template for wrangler.jsonc
 *
 * Cloudflare Workers deployment configuration.
 */

export interface WranglerConfigOptions {
  projectName: string
  domain?: string
  route?: string
  zone?: string
}

/**
 * Derive zone from domain (e.g., beads.workflows.do -> workflows.do)
 */
function deriveZone(domain: string): string {
  const parts = domain.split('.')
  // If it's a subdomain like beads.workflows.do, return workflows.do
  if (parts.length >= 3) {
    return parts.slice(-2).join('.')
  }
  return domain
}

export function generateWranglerConfig(options: WranglerConfigOptions): string {
  // Use explicit route/zone or derive from domain
  const route = options.route || (options.domain ? `${options.domain}/*` : undefined)
  const zone = options.zone || (options.domain ? deriveZone(options.domain) : undefined)

  const routeConfig = route && zone
    ? `
  "routes": [
    {
      "pattern": "${route}",
      "zone_name": "${zone}"
    }
  ],`
    : ''

  return `{
  // Generated by @mdxe/fumadocs - DO NOT EDIT
  "main": ".open-next/worker.js",
  "name": "${options.projectName.toLowerCase().replace(/[^a-z0-9-]/g, '-')}",
  "compatibility_date": "${new Date().toISOString().split('T')[0]}",
  "compatibility_flags": ["nodejs_compat", "global_fetch_strictly_public"],${routeConfig}
  "assets": {
    "directory": ".open-next/assets",
    "binding": "ASSETS"
  }
}
`
}
