/**
 * # Face parity — the assertion that makes the contract real
 *
 * Two Renderings of one Frame must agree: **every Field in the Frame appears in both, and
 * neither invents one.** That is the mechanism that lets a designer restructure any markup
 * without breaking the agent face — and it is very much cheaper than a pixel-perfect snapshot,
 * because it tests the claim that actually matters (the faces say the same thing) rather than
 * the claim that does not (the markup did not move).
 *
 * ## What it checks
 * - `snapshot` — the Rendering is of THIS Frame: same View id, same snapshot token, same `asOf`.
 *   Checked first, because two Renderings of two different moments can agree perfectly and mean
 *   nothing, and a stale face is precisely the failure this package exists to catch;
 * - `missing` — the Frame holds a Field this face never emitted;
 * - `invented` — the face emitted a path the Frame does not hold, or emitted one twice;
 * - `presence` / `attribution` — two faces disagree about one Field;
 * - `text` — a face's text differs from the Frame's canonical glyph ({@link ParityOptions.textMustMatch});
 * - cross-face text agreement ({@link ParityOptions.facesMustAgree}).
 *
 * **Those last two are separate concessions, and they used to be one.** A single `textMustMatch:
 * false` — reached for by a face that legitimately formats differently — also switched off the
 * check of every face against the Frame, so with it set, every value in every face could read
 * `DELIVERED` and parity returned clean. A caller who means "these two faces need not print the
 * same string" now says exactly that, and keeps the check that each face still matches the record.
 *
 * ## What it cannot check, said plainly
 * **Parity compares declared emissions. It never reads a body.** Every check above runs against
 * `rendering.emitted` — the `path`, `presence`, `attribution` and `text` a face claims — and
 * `faceParity` does not so much as look at `rendering.body`. A face is being taken at its word
 * about what it emitted; parity holds that word against the Frame.
 *
 * Writing a face as a {@link RenderSink} narrows this, but by less than it used to be advertised.
 * A sink's declaration is generated by the one walk (so its paths and glyphs are the walk's, not
 * the face's) and reconciled against its own bytes inside `renderFrame`. **That byte
 * reconciliation is occurrence-counting of fragments the face itself declared, over a body the
 * same face returned.** It does not relate a fragment to the glyph — `wrote: [' ']` passes for
 * every Field — and it does not relate a fragment to a position, so a face that writes the right
 * glyphs at the wrong addresses passes both reconciliation and parity. See the "Exactly what it
 * does NOT check" section in `render.ts` for the enumerated list and the verified attacks.
 *
 * So: parity catches a dropped Field, an invented path, a doubled Field, a laundered `withheld`,
 * a filled-in absence and a re-formatted number — every disagreement expressible as a difference
 * between two DECLARATIONS. It catches nothing that lives only in the bytes.
 *
 * @packageDocumentation
 */

import { FaceParityError, type ParityBreach } from './errors.js'
import type { AsOf } from './field.js'
import { framePaths, walkFrame, type Frame } from './frame.js'
import { renderGlyph } from './glyph.js'
import type { EmittedValue, Rendering } from './render.js'

/** Options for {@link faceParity} / {@link assertFaceParity}. */
export interface ParityOptions {
  /**
   * Require each face's text for a Field to equal the Frame's canonical glyph. Default `true` —
   * formatting is computed once, in the model, so a face printing different text for a Field
   * means that face computed something. Setting it `false` gives up the strongest guarantee in
   * this package: that a face's value came from the record.
   */
  readonly textMustMatch?: boolean
  /**
   * Require the faces to print the same text as EACH OTHER for a Field. Default `true`. A face
   * that legitimately differs — a React chip rendering a duration as `4d 12h` where the markdown
   * face prints the model's `4.5` — turns this off and keeps {@link textMustMatch} on, so it is
   * still held to the Frame.
   */
  readonly facesMustAgree?: boolean
  /**
   * Require every Rendering to be of this Frame's View, snapshot token and `asOf`. Default
   * `true`. There is no legitimate reason to turn it off; it exists so the check is nameable.
   */
  readonly sameSnapshot?: boolean
}

function indexEmissions(rendering: Rendering, breaches: ParityBreach[]): Map<string, EmittedValue> {
  const byPath = new Map<string, EmittedValue>()
  for (const value of rendering.emitted) {
    if (byPath.has(value.path)) {
      breaches.push({ kind: 'invented', path: value.path, detail: `face ${rendering.format} emitted this Field twice` })
      continue
    }
    byPath.set(value.path, value)
  }
  return byPath
}

function sameAsOf(a: AsOf, b: AsOf): boolean {
  if ('seq' in a) return 'seq' in b && a.seq === b.seq
  return 'instant' in b && a.instant === b.instant
}

/**
 * Every way the given Renderings disagree with the Frame or with each other. Returns an empty
 * array when they agree. Two or more Renderings may be passed; each is checked against the
 * Frame, and each is checked against the first.
 */
export function faceParity(frame: Frame, renderings: readonly Rendering[], options: ParityOptions = {}): ParityBreach[] {
  const textMustMatch = options.textMustMatch ?? true
  const facesMustAgree = options.facesMustAgree ?? true
  const sameSnapshot = options.sameSnapshot ?? true
  const breaches: ParityBreach[] = []
  const paths = framePaths(frame)
  const pathSet = new Set(paths)
  const canonical = new Map(walkFrame(frame).map((p) => [p.path, renderGlyph(p.field)]))

  if (sameSnapshot) {
    for (const rendering of renderings) {
      if (rendering.view !== frame.view) {
        breaches.push({
          kind: 'snapshot',
          path: '(frame)',
          detail: `face ${rendering.format} is a Rendering of View ${JSON.stringify(rendering.view)}; this Frame materialises ${JSON.stringify(frame.view)}`,
        })
      }
      if (rendering.snapshot.token !== frame.snapshot.token || !sameAsOf(rendering.snapshot.asOf, frame.snapshot.asOf)) {
        breaches.push({
          kind: 'snapshot',
          path: '(frame)',
          detail: `face ${rendering.format} is a Rendering of snapshot ${JSON.stringify(rendering.snapshot.token)}; this Frame is snapshot ${JSON.stringify(frame.snapshot.token)}`,
        })
      }
    }
  }

  const indexed = renderings.map((r) => ({ rendering: r, byPath: indexEmissions(r, breaches) }))

  for (const { rendering, byPath } of indexed) {
    for (const path of paths) {
      if (!byPath.has(path)) {
        breaches.push({ kind: 'missing', path, detail: `face ${rendering.format} never emitted this Field — every Field in the Frame appears in every face` })
      }
    }
    for (const value of byPath.values()) {
      if (!pathSet.has(value.path)) {
        breaches.push({
          kind: 'invented',
          path: value.path,
          detail: `face ${rendering.format} emitted ${JSON.stringify(value.text)} for a path the Frame does not hold`,
        })
        continue
      }
      const expected = canonical.get(value.path) as string
      if (textMustMatch && value.text !== expected) {
        breaches.push({
          kind: 'text',
          path: value.path,
          detail: `face ${rendering.format} emitted ${JSON.stringify(value.text)}; the Frame's canonical glyph is ${JSON.stringify(expected)}`,
        })
      }
    }
  }

  const first = indexed[0]
  if (first !== undefined) {
    for (const other of indexed.slice(1)) {
      for (const [path, a] of first.byPath) {
        const b = other.byPath.get(path)
        if (b === undefined) continue
        if (a.presence !== b.presence) {
          breaches.push({ kind: 'presence', path, detail: `${first.rendering.format} says ${a.presence}, ${other.rendering.format} says ${b.presence}` })
        }
        if (a.attribution !== b.attribution) {
          breaches.push({
            kind: 'attribution',
            path,
            detail: `${first.rendering.format} says ${a.attribution}, ${other.rendering.format} says ${b.attribution}`,
          })
        }
        if (facesMustAgree && a.text !== b.text) {
          breaches.push({
            kind: 'text',
            path,
            detail: `${first.rendering.format} emitted ${JSON.stringify(a.text)}, ${other.rendering.format} emitted ${JSON.stringify(b.text)}`,
          })
        }
      }
    }
  }

  return breaches
}

/**
 * Assert face parity, throwing a {@link FaceParityError} listing every breach. This is the call
 * that belongs in CI, once per View, over a fixture Frame that exercises all four presence
 * states and all three attributions.
 */
export function assertFaceParity(frame: Frame, renderings: readonly Rendering[], options: ParityOptions = {}): void {
  const breaches = faceParity(frame, renderings, options)
  if (breaches.length > 0) throw new FaceParityError(breaches)
}
