/**
 * # Face parity — the assertion that makes the contract real
 *
 * Two Renderings of one Frame must agree: **every Field in the Frame appears in both, and
 * neither invents one.** That is the mechanism that lets a designer restructure any markup
 * without breaking the agent face — and it is very much cheaper than a pixel-perfect snapshot,
 * because it tests the claim that actually matters (the faces say the same thing) rather than
 * the claim that does not (the markup did not move).
 *
 * ## What it checks
 * - `missing` — the Frame holds a Field this face never emitted;
 * - `invented` — the face emitted a path the Frame does not hold, or emitted one twice;
 * - `presence` / `attribution` / `text` — two faces disagree about one Field. Text equality is
 *   the default and is the strong form: both faces print the canonical glyph, so a face that
 *   rounded, re-formatted or promoted a value is caught. Pass `textMustMatch: false` for a face
 *   that legitimately differs, and accept the weaker guarantee.
 *
 * ## What it cannot check, said plainly
 * Parity compares **declared emissions**. A face built as a {@link RenderSink} has its
 * declaration generated by the one walk, so its declaration cannot drift from its bytes. A face
 * that declares its emissions by hand ({@link declareRendering}) is being taken at its word about
 * what it emitted; parity holds that word against the Frame, but it cannot see bytes the face
 * never declared. This is a real limit and the reason to write faces as sinks.
 *
 * @packageDocumentation
 */

import { FaceParityError, type ParityBreach } from './errors.js'
import { framePaths, walkFrame, type Frame } from './frame.js'
import { renderGlyph } from './glyph.js'
import type { EmittedValue, Rendering } from './render.js'

/** Options for {@link faceParity} / {@link assertFaceParity}. */
export interface ParityOptions {
  /**
   * Require both faces to print the identical canonical glyph for each Field. Default `true` —
   * formatting is computed once, in the model, so two faces printing different text for one
   * Field means one of them computed something.
   */
  readonly textMustMatch?: boolean
}

function indexEmissions(rendering: Rendering, breaches: ParityBreach[]): Map<string, EmittedValue> {
  const byPath = new Map<string, EmittedValue>()
  for (const value of rendering.emitted) {
    if (byPath.has(value.path)) {
      breaches.push({ kind: 'invented', path: value.path, detail: `face ${rendering.format} emitted this Field twice` })
      continue
    }
    byPath.set(value.path, value)
  }
  return byPath
}

/**
 * Every way the given Renderings disagree with the Frame or with each other. Returns an empty
 * array when they agree. Two or more Renderings may be passed; each is checked against the
 * Frame, and each is checked against the first.
 */
export function faceParity(frame: Frame, renderings: readonly Rendering[], options: ParityOptions = {}): ParityBreach[] {
  const textMustMatch = options.textMustMatch ?? true
  const breaches: ParityBreach[] = []
  const paths = framePaths(frame)
  const pathSet = new Set(paths)
  const canonical = new Map(walkFrame(frame).map((p) => [p.path, renderGlyph(p.field)]))

  const indexed = renderings.map((r) => ({ rendering: r, byPath: indexEmissions(r, breaches) }))

  for (const { rendering, byPath } of indexed) {
    for (const path of paths) {
      if (!byPath.has(path)) {
        breaches.push({ kind: 'missing', path, detail: `face ${rendering.format} never emitted this Field — every Field in the Frame appears in every face` })
      }
    }
    for (const value of byPath.values()) {
      if (!pathSet.has(value.path)) {
        breaches.push({
          kind: 'invented',
          path: value.path,
          detail: `face ${rendering.format} emitted ${JSON.stringify(value.text)} for a path the Frame does not hold`,
        })
        continue
      }
      const expected = canonical.get(value.path) as string
      if (textMustMatch && value.text !== expected) {
        breaches.push({
          kind: 'text',
          path: value.path,
          detail: `face ${rendering.format} emitted ${JSON.stringify(value.text)}; the Frame's canonical glyph is ${JSON.stringify(expected)}`,
        })
      }
    }
  }

  const first = indexed[0]
  if (first !== undefined) {
    for (const other of indexed.slice(1)) {
      for (const [path, a] of first.byPath) {
        const b = other.byPath.get(path)
        if (b === undefined) continue
        if (a.presence !== b.presence) {
          breaches.push({ kind: 'presence', path, detail: `${first.rendering.format} says ${a.presence}, ${other.rendering.format} says ${b.presence}` })
        }
        if (a.attribution !== b.attribution) {
          breaches.push({
            kind: 'attribution',
            path,
            detail: `${first.rendering.format} says ${a.attribution}, ${other.rendering.format} says ${b.attribution}`,
          })
        }
        if (textMustMatch && a.text !== b.text) {
          breaches.push({
            kind: 'text',
            path,
            detail: `${first.rendering.format} emitted ${JSON.stringify(a.text)}, ${other.rendering.format} emitted ${JSON.stringify(b.text)}`,
          })
        }
      }
    }
  }

  return breaches
}

/**
 * Assert face parity, throwing a {@link FaceParityError} listing every breach. This is the call
 * that belongs in CI, once per View, over a fixture Frame that exercises all four presence
 * states and all three attributions.
 */
export function assertFaceParity(frame: Frame, renderings: readonly Rendering[], options: ParityOptions = {}): void {
  const breaches = faceParity(frame, renderings, options)
  if (breaches.length > 0) throw new FaceParityError(breaches)
}
