/**
 * Theme presets from tweakcn
 *
 * @see https://github.com/jnsahaj/tweakcn
 * @see https://tweakcn.com
 */

import type { ThemePreset, ThemePresets } from './types.js'

/**
 * Modern Minimal - Clean blue palette with minimal styling
 */
export const modernMinimal: ThemePreset = {
  label: 'Modern Minimal',
  styles: {
    light: {
      background: '#ffffff',
      foreground: '#0a0a0a',
      card: '#ffffff',
      'card-foreground': '#0a0a0a',
      popover: '#ffffff',
      'popover-foreground': '#0a0a0a',
      primary: '#3b82f6',
      'primary-foreground': '#ffffff',
      secondary: '#f1f5f9',
      'secondary-foreground': '#0f172a',
      muted: '#f1f5f9',
      'muted-foreground': '#64748b',
      accent: '#f1f5f9',
      'accent-foreground': '#0f172a',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#e2e8f0',
      input: '#e2e8f0',
      ring: '#3b82f6',
      radius: '0.5rem',
    },
    dark: {
      background: '#0a0a0a',
      foreground: '#fafafa',
      card: '#0a0a0a',
      'card-foreground': '#fafafa',
      popover: '#0a0a0a',
      'popover-foreground': '#fafafa',
      primary: '#3b82f6',
      'primary-foreground': '#ffffff',
      secondary: '#1e293b',
      'secondary-foreground': '#f8fafc',
      muted: '#1e293b',
      'muted-foreground': '#94a3b8',
      accent: '#1e293b',
      'accent-foreground': '#f8fafc',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#1e293b',
      input: '#1e293b',
      ring: '#3b82f6',
      radius: '0.5rem',
    },
  },
}

/**
 * Violet Bloom - Rich purple theme with custom shadows
 */
export const violetBloom: ThemePreset = {
  label: 'Violet Bloom',
  styles: {
    light: {
      background: '#faf8ff',
      foreground: '#1a1523',
      card: '#ffffff',
      'card-foreground': '#1a1523',
      popover: '#ffffff',
      'popover-foreground': '#1a1523',
      primary: '#7033ff',
      'primary-foreground': '#ffffff',
      secondary: '#f3f0ff',
      'secondary-foreground': '#1a1523',
      muted: '#f3f0ff',
      'muted-foreground': '#6b5f7c',
      accent: '#f3f0ff',
      'accent-foreground': '#1a1523',
      destructive: '#e93d3d',
      'destructive-foreground': '#ffffff',
      border: '#e4dff0',
      input: '#e4dff0',
      ring: '#7033ff',
      radius: '1.4rem',
      'letter-spacing': '-0.025em',
    },
    dark: {
      background: '#0f0a1a',
      foreground: '#f5f3ff',
      card: '#1a1228',
      'card-foreground': '#f5f3ff',
      popover: '#1a1228',
      'popover-foreground': '#f5f3ff',
      primary: '#9966ff',
      'primary-foreground': '#ffffff',
      secondary: '#2d2640',
      'secondary-foreground': '#f5f3ff',
      muted: '#2d2640',
      'muted-foreground': '#a89fc4',
      accent: '#2d2640',
      'accent-foreground': '#f5f3ff',
      destructive: '#ff6b6b',
      'destructive-foreground': '#ffffff',
      border: '#3d3356',
      input: '#3d3356',
      ring: '#9966ff',
      radius: '1.4rem',
      'letter-spacing': '-0.025em',
    },
  },
}

/**
 * T3 Chat - Warm purple theme inspired by T3 Stack
 */
export const t3Chat: ThemePreset = {
  label: 'T3 Chat',
  styles: {
    light: {
      background: '#fefcfb',
      foreground: '#1c1917',
      card: '#ffffff',
      'card-foreground': '#1c1917',
      popover: '#ffffff',
      'popover-foreground': '#1c1917',
      primary: '#a84370',
      'primary-foreground': '#ffffff',
      secondary: '#fdf2f8',
      'secondary-foreground': '#1c1917',
      muted: '#f5f5f4',
      'muted-foreground': '#78716c',
      accent: '#fdf2f8',
      'accent-foreground': '#1c1917',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#e7e5e4',
      input: '#e7e5e4',
      ring: '#a84370',
      radius: '0.75rem',
      sidebar: '#faf5f3',
      'sidebar-foreground': '#1c1917',
      'sidebar-primary': '#a84370',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#fdf2f8',
      'sidebar-accent-foreground': '#1c1917',
      'sidebar-border': '#e7e5e4',
    },
    dark: {
      background: '#0c0a09',
      foreground: '#fafaf9',
      card: '#1c1917',
      'card-foreground': '#fafaf9',
      popover: '#1c1917',
      'popover-foreground': '#fafaf9',
      primary: '#db7093',
      'primary-foreground': '#0c0a09',
      secondary: '#292524',
      'secondary-foreground': '#fafaf9',
      muted: '#292524',
      'muted-foreground': '#a8a29e',
      accent: '#44403c',
      'accent-foreground': '#fafaf9',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#292524',
      input: '#292524',
      ring: '#db7093',
      radius: '0.75rem',
      sidebar: '#1c1917',
      'sidebar-foreground': '#fafaf9',
      'sidebar-primary': '#db7093',
      'sidebar-primary-foreground': '#0c0a09',
      'sidebar-accent': '#292524',
      'sidebar-accent-foreground': '#fafaf9',
      'sidebar-border': '#292524',
    },
  },
}

/**
 * Twitter - Twitter/X inspired blue theme
 */
export const twitter: ThemePreset = {
  label: 'Twitter',
  styles: {
    light: {
      background: '#ffffff',
      foreground: '#0f1419',
      card: '#ffffff',
      'card-foreground': '#0f1419',
      popover: '#ffffff',
      'popover-foreground': '#0f1419',
      primary: '#1d9bf0',
      'primary-foreground': '#ffffff',
      secondary: '#eff3f4',
      'secondary-foreground': '#0f1419',
      muted: '#f7f9f9',
      'muted-foreground': '#536471',
      accent: '#eff3f4',
      'accent-foreground': '#0f1419',
      destructive: '#f4212e',
      'destructive-foreground': '#ffffff',
      border: '#eff3f4',
      input: '#eff3f4',
      ring: '#1d9bf0',
      radius: '9999px',
    },
    dark: {
      background: '#000000',
      foreground: '#e7e9ea',
      card: '#16181c',
      'card-foreground': '#e7e9ea',
      popover: '#16181c',
      'popover-foreground': '#e7e9ea',
      primary: '#1d9bf0',
      'primary-foreground': '#ffffff',
      secondary: '#202327',
      'secondary-foreground': '#e7e9ea',
      muted: '#2f3336',
      'muted-foreground': '#71767b',
      accent: '#202327',
      'accent-foreground': '#e7e9ea',
      destructive: '#f4212e',
      'destructive-foreground': '#ffffff',
      border: '#2f3336',
      input: '#2f3336',
      ring: '#1d9bf0',
      radius: '9999px',
    },
  },
}

/**
 * Mocha Mousse - Pantone 2025 Color of the Year inspired
 */
export const mochaMousse: ThemePreset = {
  label: 'Mocha Mousse',
  styles: {
    light: {
      background: '#faf7f5',
      foreground: '#3d2f27',
      card: '#ffffff',
      'card-foreground': '#3d2f27',
      popover: '#ffffff',
      'popover-foreground': '#3d2f27',
      primary: '#a47764',
      'primary-foreground': '#ffffff',
      secondary: '#f5ebe6',
      'secondary-foreground': '#3d2f27',
      muted: '#f0e6df',
      'muted-foreground': '#7a6459',
      accent: '#e8d5c9',
      'accent-foreground': '#3d2f27',
      destructive: '#c45a4e',
      'destructive-foreground': '#ffffff',
      border: '#e0d4ca',
      input: '#e0d4ca',
      ring: '#a47764',
      radius: '0.5rem',
    },
    dark: {
      background: '#1c1614',
      foreground: '#f5ebe6',
      card: '#2a211d',
      'card-foreground': '#f5ebe6',
      popover: '#2a211d',
      'popover-foreground': '#f5ebe6',
      primary: '#c9a090',
      'primary-foreground': '#1c1614',
      secondary: '#3d312a',
      'secondary-foreground': '#f5ebe6',
      muted: '#4a3d35',
      'muted-foreground': '#b8a99e',
      accent: '#4a3d35',
      'accent-foreground': '#f5ebe6',
      destructive: '#e07468',
      'destructive-foreground': '#ffffff',
      border: '#4a3d35',
      input: '#4a3d35',
      ring: '#c9a090',
      radius: '0.5rem',
    },
  },
}

/**
 * Bubblegum - Playful pink theme
 */
export const bubblegum: ThemePreset = {
  label: 'Bubblegum',
  styles: {
    light: {
      background: '#fff5f8',
      foreground: '#2d1f24',
      card: '#ffffff',
      'card-foreground': '#2d1f24',
      popover: '#ffffff',
      'popover-foreground': '#2d1f24',
      primary: '#ff6b9d',
      'primary-foreground': '#ffffff',
      secondary: '#ffe4ec',
      'secondary-foreground': '#2d1f24',
      muted: '#fce7ee',
      'muted-foreground': '#8a6672',
      accent: '#ffd1de',
      'accent-foreground': '#2d1f24',
      destructive: '#e8384f',
      'destructive-foreground': '#ffffff',
      border: '#ffd6e3',
      input: '#ffd6e3',
      ring: '#ff6b9d',
      radius: '1rem',
    },
    dark: {
      background: '#1a0f13',
      foreground: '#ffe4ec',
      card: '#2a1a20',
      'card-foreground': '#ffe4ec',
      popover: '#2a1a20',
      'popover-foreground': '#ffe4ec',
      primary: '#ff8fb8',
      'primary-foreground': '#1a0f13',
      secondary: '#3d2730',
      'secondary-foreground': '#ffe4ec',
      muted: '#4a2f38',
      'muted-foreground': '#c9a3b0',
      accent: '#4a2f38',
      'accent-foreground': '#ffe4ec',
      destructive: '#ff6b7a',
      'destructive-foreground': '#ffffff',
      border: '#4a2f38',
      input: '#4a2f38',
      ring: '#ff8fb8',
      radius: '1rem',
    },
  },
}

/**
 * Catppuccin - Popular pastel theme
 */
export const catppuccin: ThemePreset = {
  label: 'Catppuccin',
  styles: {
    light: {
      background: '#eff1f5',
      foreground: '#4c4f69',
      card: '#e6e9ef',
      'card-foreground': '#4c4f69',
      popover: '#e6e9ef',
      'popover-foreground': '#4c4f69',
      primary: '#8839ef',
      'primary-foreground': '#eff1f5',
      secondary: '#dce0e8',
      'secondary-foreground': '#4c4f69',
      muted: '#ccd0da',
      'muted-foreground': '#6c6f85',
      accent: '#ccd0da',
      'accent-foreground': '#4c4f69',
      destructive: '#d20f39',
      'destructive-foreground': '#eff1f5',
      border: '#bcc0cc',
      input: '#bcc0cc',
      ring: '#8839ef',
      radius: '0.5rem',
      'chart-1': '#8839ef',
      'chart-2': '#1e66f5',
      'chart-3': '#179299',
      'chart-4': '#40a02b',
      'chart-5': '#df8e1d',
    },
    dark: {
      background: '#1e1e2e',
      foreground: '#cdd6f4',
      card: '#313244',
      'card-foreground': '#cdd6f4',
      popover: '#313244',
      'popover-foreground': '#cdd6f4',
      primary: '#cba6f7',
      'primary-foreground': '#1e1e2e',
      secondary: '#45475a',
      'secondary-foreground': '#cdd6f4',
      muted: '#585b70',
      'muted-foreground': '#a6adc8',
      accent: '#585b70',
      'accent-foreground': '#cdd6f4',
      destructive: '#f38ba8',
      'destructive-foreground': '#1e1e2e',
      border: '#45475a',
      input: '#45475a',
      ring: '#cba6f7',
      radius: '0.5rem',
      'chart-1': '#cba6f7',
      'chart-2': '#89b4fa',
      'chart-3': '#94e2d5',
      'chart-4': '#a6e3a1',
      'chart-5': '#f9e2af',
    },
  },
}

/**
 * Graphite - Neutral gray theme
 */
export const graphite: ThemePreset = {
  label: 'Graphite',
  styles: {
    light: {
      background: '#fafafa',
      foreground: '#18181b',
      card: '#ffffff',
      'card-foreground': '#18181b',
      popover: '#ffffff',
      'popover-foreground': '#18181b',
      primary: '#52525b',
      'primary-foreground': '#fafafa',
      secondary: '#f4f4f5',
      'secondary-foreground': '#18181b',
      muted: '#e4e4e7',
      'muted-foreground': '#71717a',
      accent: '#e4e4e7',
      'accent-foreground': '#18181b',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#d4d4d8',
      input: '#d4d4d8',
      ring: '#52525b',
      radius: '0.375rem',
    },
    dark: {
      background: '#09090b',
      foreground: '#fafafa',
      card: '#18181b',
      'card-foreground': '#fafafa',
      popover: '#18181b',
      'popover-foreground': '#fafafa',
      primary: '#a1a1aa',
      'primary-foreground': '#09090b',
      secondary: '#27272a',
      'secondary-foreground': '#fafafa',
      muted: '#3f3f46',
      'muted-foreground': '#a1a1aa',
      accent: '#3f3f46',
      'accent-foreground': '#fafafa',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#27272a',
      input: '#27272a',
      ring: '#a1a1aa',
      radius: '0.375rem',
    },
  },
}

/**
 * Cyberpunk - Neon cyberpunk aesthetic
 */
export const cyberpunk: ThemePreset = {
  label: 'Cyberpunk',
  styles: {
    light: {
      background: '#f0f0f5',
      foreground: '#1a1a2e',
      card: '#ffffff',
      'card-foreground': '#1a1a2e',
      popover: '#ffffff',
      'popover-foreground': '#1a1a2e',
      primary: '#ff00ff',
      'primary-foreground': '#ffffff',
      secondary: '#00ffff',
      'secondary-foreground': '#1a1a2e',
      muted: '#e0e0e8',
      'muted-foreground': '#4a4a6a',
      accent: '#ffff00',
      'accent-foreground': '#1a1a2e',
      destructive: '#ff0055',
      'destructive-foreground': '#ffffff',
      border: '#ccccdd',
      input: '#ccccdd',
      ring: '#ff00ff',
      radius: '0',
    },
    dark: {
      background: '#0a0a15',
      foreground: '#e0e0ff',
      card: '#1a1a2e',
      'card-foreground': '#e0e0ff',
      popover: '#1a1a2e',
      'popover-foreground': '#e0e0ff',
      primary: '#ff00ff',
      'primary-foreground': '#000000',
      secondary: '#00ffff',
      'secondary-foreground': '#000000',
      muted: '#2a2a4e',
      'muted-foreground': '#8080a0',
      accent: '#ffff00',
      'accent-foreground': '#000000',
      destructive: '#ff0055',
      'destructive-foreground': '#ffffff',
      border: '#3a3a5e',
      input: '#3a3a5e',
      ring: '#ff00ff',
      radius: '0',
    },
  },
}

/**
 * Neo Brutalism - Bold, blocky design
 */
export const neoBrutalism: ThemePreset = {
  label: 'Neo Brutalism',
  styles: {
    light: {
      background: '#fffef5',
      foreground: '#000000',
      card: '#ffffff',
      'card-foreground': '#000000',
      popover: '#ffffff',
      'popover-foreground': '#000000',
      primary: '#ff5555',
      'primary-foreground': '#000000',
      secondary: '#ffdd55',
      'secondary-foreground': '#000000',
      muted: '#f5f5dc',
      'muted-foreground': '#333333',
      accent: '#55ff55',
      'accent-foreground': '#000000',
      destructive: '#ff0000',
      'destructive-foreground': '#ffffff',
      border: '#000000',
      input: '#000000',
      ring: '#000000',
      radius: '0',
      'shadow-color': '#000000',
      'shadow-offset-x': '4px',
      'shadow-offset-y': '4px',
      'shadow-blur': '0',
      'shadow-spread': '0',
    },
    dark: {
      background: '#1a1a1a',
      foreground: '#ffffff',
      card: '#2a2a2a',
      'card-foreground': '#ffffff',
      popover: '#2a2a2a',
      'popover-foreground': '#ffffff',
      primary: '#ff5555',
      'primary-foreground': '#ffffff',
      secondary: '#ffdd55',
      'secondary-foreground': '#000000',
      muted: '#3a3a3a',
      'muted-foreground': '#cccccc',
      accent: '#55ff55',
      'accent-foreground': '#000000',
      destructive: '#ff3333',
      'destructive-foreground': '#ffffff',
      border: '#ffffff',
      input: '#ffffff',
      ring: '#ffffff',
      radius: '0',
      'shadow-color': '#ffffff',
      'shadow-offset-x': '4px',
      'shadow-offset-y': '4px',
      'shadow-blur': '0',
      'shadow-spread': '0',
    },
  },
}

/**
 * Ocean Breeze - Calm oceanic theme
 */
export const oceanBreeze: ThemePreset = {
  label: 'Ocean Breeze',
  styles: {
    light: {
      background: '#f5fafa',
      foreground: '#0a3d4c',
      card: '#ffffff',
      'card-foreground': '#0a3d4c',
      popover: '#ffffff',
      'popover-foreground': '#0a3d4c',
      primary: '#0891b2',
      'primary-foreground': '#ffffff',
      secondary: '#e0f7fa',
      'secondary-foreground': '#0a3d4c',
      muted: '#e0f2f1',
      'muted-foreground': '#4a7c86',
      accent: '#b2ebf2',
      'accent-foreground': '#0a3d4c',
      destructive: '#e53935',
      'destructive-foreground': '#ffffff',
      border: '#b2dfdb',
      input: '#b2dfdb',
      ring: '#0891b2',
      radius: '0.75rem',
    },
    dark: {
      background: '#0a1a1f',
      foreground: '#e0f7fa',
      card: '#0f2930',
      'card-foreground': '#e0f7fa',
      popover: '#0f2930',
      'popover-foreground': '#e0f7fa',
      primary: '#22d3ee',
      'primary-foreground': '#0a1a1f',
      secondary: '#164e56',
      'secondary-foreground': '#e0f7fa',
      muted: '#1e3a40',
      'muted-foreground': '#80cbc4',
      accent: '#1e3a40',
      'accent-foreground': '#e0f7fa',
      destructive: '#ef5350',
      'destructive-foreground': '#ffffff',
      border: '#1e3a40',
      input: '#1e3a40',
      ring: '#22d3ee',
      radius: '0.75rem',
    },
  },
}

/**
 * Supabase - Supabase brand colors
 */
export const supabase: ThemePreset = {
  label: 'Supabase',
  styles: {
    light: {
      background: '#ffffff',
      foreground: '#171717',
      card: '#ffffff',
      'card-foreground': '#171717',
      popover: '#ffffff',
      'popover-foreground': '#171717',
      primary: '#3ecf8e',
      'primary-foreground': '#171717',
      secondary: '#f1f5f1',
      'secondary-foreground': '#171717',
      muted: '#f5f5f5',
      'muted-foreground': '#737373',
      accent: '#e9fff4',
      'accent-foreground': '#171717',
      destructive: '#f43f5e',
      'destructive-foreground': '#ffffff',
      border: '#e5e5e5',
      input: '#e5e5e5',
      ring: '#3ecf8e',
      radius: '0.5rem',
    },
    dark: {
      background: '#171717',
      foreground: '#ededed',
      card: '#1c1c1c',
      'card-foreground': '#ededed',
      popover: '#1c1c1c',
      'popover-foreground': '#ededed',
      primary: '#3ecf8e',
      'primary-foreground': '#171717',
      secondary: '#2a2a2a',
      'secondary-foreground': '#ededed',
      muted: '#2a2a2a',
      'muted-foreground': '#a3a3a3',
      accent: '#1e3a2f',
      'accent-foreground': '#ededed',
      destructive: '#f43f5e',
      'destructive-foreground': '#ffffff',
      border: '#2a2a2a',
      input: '#2a2a2a',
      ring: '#3ecf8e',
      radius: '0.5rem',
    },
  },
}

/**
 * Sunset Horizon - Warm sunset gradient theme
 */
export const sunsetHorizon: ThemePreset = {
  label: 'Sunset Horizon',
  styles: {
    light: {
      background: '#fffaf5',
      foreground: '#2d1810',
      card: '#ffffff',
      'card-foreground': '#2d1810',
      popover: '#ffffff',
      'popover-foreground': '#2d1810',
      primary: '#f97316',
      'primary-foreground': '#ffffff',
      secondary: '#fed7aa',
      'secondary-foreground': '#2d1810',
      muted: '#ffedd5',
      'muted-foreground': '#9a3412',
      accent: '#fef3c7',
      'accent-foreground': '#2d1810',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#fdba74',
      input: '#fdba74',
      ring: '#f97316',
      radius: '0.625rem',
    },
    dark: {
      background: '#1c0f0a',
      foreground: '#fff7ed',
      card: '#2d1810',
      'card-foreground': '#fff7ed',
      popover: '#2d1810',
      'popover-foreground': '#fff7ed',
      primary: '#fb923c',
      'primary-foreground': '#1c0f0a',
      secondary: '#431407',
      'secondary-foreground': '#fff7ed',
      muted: '#3d1f12',
      'muted-foreground': '#fdba74',
      accent: '#3d1f12',
      'accent-foreground': '#fff7ed',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#431407',
      input: '#431407',
      ring: '#fb923c',
      radius: '0.625rem',
    },
  },
}

/**
 * Northern Lights - Aurora inspired theme
 */
export const northernLights: ThemePreset = {
  label: 'Northern Lights',
  styles: {
    light: {
      background: '#f0f9ff',
      foreground: '#0c1929',
      card: '#ffffff',
      'card-foreground': '#0c1929',
      popover: '#ffffff',
      'popover-foreground': '#0c1929',
      primary: '#06b6d4',
      'primary-foreground': '#ffffff',
      secondary: '#d1fae5',
      'secondary-foreground': '#0c1929',
      muted: '#e0f2fe',
      'muted-foreground': '#475569',
      accent: '#c4b5fd',
      'accent-foreground': '#0c1929',
      destructive: '#f43f5e',
      'destructive-foreground': '#ffffff',
      border: '#a5f3fc',
      input: '#a5f3fc',
      ring: '#06b6d4',
      radius: '0.75rem',
    },
    dark: {
      background: '#020617',
      foreground: '#f0f9ff',
      card: '#0c1929',
      'card-foreground': '#f0f9ff',
      popover: '#0c1929',
      'popover-foreground': '#f0f9ff',
      primary: '#22d3ee',
      'primary-foreground': '#020617',
      secondary: '#064e3b',
      'secondary-foreground': '#f0f9ff',
      muted: '#0f2942',
      'muted-foreground': '#94a3b8',
      accent: '#4c1d95',
      'accent-foreground': '#f0f9ff',
      destructive: '#fb7185',
      'destructive-foreground': '#020617',
      border: '#164e63',
      input: '#164e63',
      ring: '#22d3ee',
      radius: '0.75rem',
    },
  },
}

/**
 * Claude - Anthropic Claude brand colors
 */
export const claude: ThemePreset = {
  label: 'Claude',
  styles: {
    light: {
      background: '#faf9f7',
      foreground: '#1a1a1a',
      card: '#ffffff',
      'card-foreground': '#1a1a1a',
      popover: '#ffffff',
      'popover-foreground': '#1a1a1a',
      primary: '#da7756',
      'primary-foreground': '#ffffff',
      secondary: '#f5f1eb',
      'secondary-foreground': '#1a1a1a',
      muted: '#f0ebe3',
      'muted-foreground': '#6b6b6b',
      accent: '#f5f1eb',
      'accent-foreground': '#1a1a1a',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#e5e0d8',
      input: '#e5e0d8',
      ring: '#da7756',
      radius: '0.5rem',
    },
    dark: {
      background: '#1a1a1a',
      foreground: '#f5f1eb',
      card: '#262626',
      'card-foreground': '#f5f1eb',
      popover: '#262626',
      'popover-foreground': '#f5f1eb',
      primary: '#e8956a',
      'primary-foreground': '#1a1a1a',
      secondary: '#333333',
      'secondary-foreground': '#f5f1eb',
      muted: '#404040',
      'muted-foreground': '#a3a3a3',
      accent: '#333333',
      'accent-foreground': '#f5f1eb',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#404040',
      input: '#404040',
      ring: '#e8956a',
      radius: '0.5rem',
    },
  },
}

/**
 * Retro Arcade - 80s arcade aesthetic
 */
export const retroArcade: ThemePreset = {
  label: 'Retro Arcade',
  styles: {
    light: {
      background: '#1a0a2e',
      foreground: '#00ff88',
      card: '#2a1a4e',
      'card-foreground': '#00ff88',
      popover: '#2a1a4e',
      'popover-foreground': '#00ff88',
      primary: '#ff00ff',
      'primary-foreground': '#ffffff',
      secondary: '#00ffff',
      'secondary-foreground': '#1a0a2e',
      muted: '#3a2a5e',
      'muted-foreground': '#80ffcc',
      accent: '#ffff00',
      'accent-foreground': '#1a0a2e',
      destructive: '#ff0055',
      'destructive-foreground': '#ffffff',
      border: '#ff00ff',
      input: '#4a3a7e',
      ring: '#ff00ff',
      radius: '0',
    },
    dark: {
      background: '#0a0515',
      foreground: '#00ff88',
      card: '#1a0a2e',
      'card-foreground': '#00ff88',
      popover: '#1a0a2e',
      'popover-foreground': '#00ff88',
      primary: '#ff00ff',
      'primary-foreground': '#ffffff',
      secondary: '#00ffff',
      'secondary-foreground': '#0a0515',
      muted: '#2a1a4e',
      'muted-foreground': '#80ffcc',
      accent: '#ffff00',
      'accent-foreground': '#0a0515',
      destructive: '#ff0055',
      'destructive-foreground': '#ffffff',
      border: '#ff00ff',
      input: '#3a2a5e',
      ring: '#ff00ff',
      radius: '0',
    },
  },
}

/**
 * Pastel Dreams - Soft pastel colors
 */
export const pastelDreams: ThemePreset = {
  label: 'Pastel Dreams',
  styles: {
    light: {
      background: '#fef7f8',
      foreground: '#3d3d4e',
      card: '#ffffff',
      'card-foreground': '#3d3d4e',
      popover: '#ffffff',
      'popover-foreground': '#3d3d4e',
      primary: '#f5b5c8',
      'primary-foreground': '#3d3d4e',
      secondary: '#c5e8d5',
      'secondary-foreground': '#3d3d4e',
      muted: '#f0e5e8',
      'muted-foreground': '#7a7a8c',
      accent: '#e5d5f5',
      'accent-foreground': '#3d3d4e',
      destructive: '#f5a5a5',
      'destructive-foreground': '#3d3d4e',
      border: '#e8d8e0',
      input: '#e8d8e0',
      ring: '#f5b5c8',
      radius: '1rem',
    },
    dark: {
      background: '#1e1e28',
      foreground: '#e8e8f0',
      card: '#28283a',
      'card-foreground': '#e8e8f0',
      popover: '#28283a',
      'popover-foreground': '#e8e8f0',
      primary: '#d4899f',
      'primary-foreground': '#1e1e28',
      secondary: '#7ab89e',
      'secondary-foreground': '#1e1e28',
      muted: '#3a3a4e',
      'muted-foreground': '#a8a8b8',
      accent: '#9e88b8',
      'accent-foreground': '#1e1e28',
      destructive: '#c88888',
      'destructive-foreground': '#1e1e28',
      border: '#3a3a4e',
      input: '#3a3a4e',
      ring: '#d4899f',
      radius: '1rem',
    },
  },
}

/**
 * Nature - Earthy green theme
 */
export const nature: ThemePreset = {
  label: 'Nature',
  styles: {
    light: {
      background: '#f5f9f5',
      foreground: '#1a2e1a',
      card: '#ffffff',
      'card-foreground': '#1a2e1a',
      popover: '#ffffff',
      'popover-foreground': '#1a2e1a',
      primary: '#4a9f5a',
      'primary-foreground': '#ffffff',
      secondary: '#d5ecd5',
      'secondary-foreground': '#1a2e1a',
      muted: '#e5f0e5',
      'muted-foreground': '#4a6b4a',
      accent: '#c5e0c5',
      'accent-foreground': '#1a2e1a',
      destructive: '#c44a4a',
      'destructive-foreground': '#ffffff',
      border: '#c5dac5',
      input: '#c5dac5',
      ring: '#4a9f5a',
      radius: '0.5rem',
    },
    dark: {
      background: '#0a150a',
      foreground: '#d5ecd5',
      card: '#152015',
      'card-foreground': '#d5ecd5',
      popover: '#152015',
      'popover-foreground': '#d5ecd5',
      primary: '#6abf7a',
      'primary-foreground': '#0a150a',
      secondary: '#2a402a',
      'secondary-foreground': '#d5ecd5',
      muted: '#1f2f1f',
      'muted-foreground': '#8ab08a',
      accent: '#2a402a',
      'accent-foreground': '#d5ecd5',
      destructive: '#e06a6a',
      'destructive-foreground': '#ffffff',
      border: '#2a402a',
      input: '#2a402a',
      ring: '#6abf7a',
      radius: '0.5rem',
    },
  },
}

/**
 * Caffeine - Coffee inspired warm brown theme
 */
export const caffeine: ThemePreset = {
  label: 'Caffeine',
  styles: {
    light: {
      background: '#faf8f5',
      foreground: '#2d2520',
      card: '#ffffff',
      'card-foreground': '#2d2520',
      popover: '#ffffff',
      'popover-foreground': '#2d2520',
      primary: '#8b5a2b',
      'primary-foreground': '#ffffff',
      secondary: '#f0e6d8',
      'secondary-foreground': '#2d2520',
      muted: '#e8ddd0',
      'muted-foreground': '#6b5a4d',
      accent: '#d4c4b0',
      'accent-foreground': '#2d2520',
      destructive: '#c44a4a',
      'destructive-foreground': '#ffffff',
      border: '#d8ccbd',
      input: '#d8ccbd',
      ring: '#8b5a2b',
      radius: '0.375rem',
    },
    dark: {
      background: '#1a1512',
      foreground: '#f0e6d8',
      card: '#2d2520',
      'card-foreground': '#f0e6d8',
      popover: '#2d2520',
      'popover-foreground': '#f0e6d8',
      primary: '#c8a070',
      'primary-foreground': '#1a1512',
      secondary: '#3d3530',
      'secondary-foreground': '#f0e6d8',
      muted: '#4a403a',
      'muted-foreground': '#b0a090',
      accent: '#4a403a',
      'accent-foreground': '#f0e6d8',
      destructive: '#e06a6a',
      'destructive-foreground': '#ffffff',
      border: '#4a403a',
      input: '#4a403a',
      ring: '#c8a070',
      radius: '0.375rem',
    },
  },
}

/**
 * Elegant Luxury - Sophisticated dark theme with gold accents
 */
export const elegantLuxury: ThemePreset = {
  label: 'Elegant Luxury',
  styles: {
    light: {
      background: '#faf9f7',
      foreground: '#1a1a1a',
      card: '#ffffff',
      'card-foreground': '#1a1a1a',
      popover: '#ffffff',
      'popover-foreground': '#1a1a1a',
      primary: '#b8860b',
      'primary-foreground': '#ffffff',
      secondary: '#f5f0e6',
      'secondary-foreground': '#1a1a1a',
      muted: '#ebe5d8',
      'muted-foreground': '#6b6b6b',
      accent: '#e0d5c0',
      'accent-foreground': '#1a1a1a',
      destructive: '#8b0000',
      'destructive-foreground': '#ffffff',
      border: '#d4c9b8',
      input: '#d4c9b8',
      ring: '#b8860b',
      radius: '0.25rem',
      'letter-spacing': '0.05em',
    },
    dark: {
      background: '#0a0a0a',
      foreground: '#f5f0e6',
      card: '#1a1a1a',
      'card-foreground': '#f5f0e6',
      popover: '#1a1a1a',
      'popover-foreground': '#f5f0e6',
      primary: '#daa520',
      'primary-foreground': '#0a0a0a',
      secondary: '#2a2520',
      'secondary-foreground': '#f5f0e6',
      muted: '#3a3530',
      'muted-foreground': '#a0988c',
      accent: '#3a3530',
      'accent-foreground': '#f5f0e6',
      destructive: '#dc143c',
      'destructive-foreground': '#ffffff',
      border: '#3a3530',
      input: '#3a3530',
      ring: '#daa520',
      radius: '0.25rem',
      'letter-spacing': '0.05em',
    },
  },
}

/**
 * Clean Slate - Minimal clean design
 */
export const cleanSlate: ThemePreset = {
  label: 'Clean Slate',
  styles: {
    light: {
      background: '#ffffff',
      foreground: '#1e293b',
      card: '#ffffff',
      'card-foreground': '#1e293b',
      popover: '#ffffff',
      'popover-foreground': '#1e293b',
      primary: '#475569',
      'primary-foreground': '#ffffff',
      secondary: '#f8fafc',
      'secondary-foreground': '#1e293b',
      muted: '#f1f5f9',
      'muted-foreground': '#64748b',
      accent: '#f1f5f9',
      'accent-foreground': '#1e293b',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#e2e8f0',
      input: '#e2e8f0',
      ring: '#475569',
      radius: '0.5rem',
    },
    dark: {
      background: '#0f172a',
      foreground: '#f8fafc',
      card: '#1e293b',
      'card-foreground': '#f8fafc',
      popover: '#1e293b',
      'popover-foreground': '#f8fafc',
      primary: '#94a3b8',
      'primary-foreground': '#0f172a',
      secondary: '#334155',
      'secondary-foreground': '#f8fafc',
      muted: '#334155',
      'muted-foreground': '#94a3b8',
      accent: '#334155',
      'accent-foreground': '#f8fafc',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#334155',
      input: '#334155',
      ring: '#94a3b8',
      radius: '0.5rem',
    },
  },
}

/**
 * All default presets
 */
export const defaultPresets: ThemePresets = {
  'modern-minimal': modernMinimal,
  'violet-bloom': violetBloom,
  't3-chat': t3Chat,
  twitter: twitter,
  'mocha-mousse': mochaMousse,
  bubblegum: bubblegum,
  catppuccin: catppuccin,
  graphite: graphite,
  cyberpunk: cyberpunk,
  'neo-brutalism': neoBrutalism,
  'ocean-breeze': oceanBreeze,
  supabase: supabase,
  'sunset-horizon': sunsetHorizon,
  'northern-lights': northernLights,
  claude: claude,
  'retro-arcade': retroArcade,
  'pastel-dreams': pastelDreams,
  nature: nature,
  caffeine: caffeine,
  'elegant-luxury': elegantLuxury,
  'clean-slate': cleanSlate,
}

/**
 * Get a theme preset by name
 */
export function getPreset(name: string): ThemePreset | undefined {
  return defaultPresets[name]
}

/**
 * Get all preset names
 */
export function getPresetNames(): string[] {
  return Object.keys(defaultPresets)
}

/**
 * Default preset name
 */
export const DEFAULT_PRESET = 'modern-minimal'
