/**
 * Auto-generated Site Stories
 *
 * This file is automatically generated from the @mdxui/examples site registry.
 * To regenerate: npx @mdxui/storybook generate-stories
 */

import type { Meta, StoryObj } from '@storybook/react'
import React from 'react'
import { siteRegistry } from '@mdxui/examples'
import {
  AgenticSite,
  agenticData,
  AdvertisSite,
  advertisData,
  WorkflowSite,
  workflowData,
  ScrapeSite,
  scrapeData,
  ApiHtSite,
  apiHtData,
  DbHtSite,
  dbHtData,
  HeadlessSite,
  headlessData,
  MarktSite,
  marktData,
} from '@mdxui/examples'
import { DuskLayout, QuartzLayout, MistLayout } from '@mdxui/tailark/templates'
import { ScalarLayout, SonicLayout, LumenLayout } from '@mdxui/shadcnblocks/templates'

const SiteRenderer: React.FC<{ siteId?: string }> = ({ siteId }) => {
  const sites: Record<string, React.FC> = {
    agentic: AgenticSite,
    advertis: AdvertisSite,
    workflow: WorkflowSite,
    scrape: ScrapeSite,
    apiHt: ApiHtSite,
    dbHt: DbHtSite,
    headless: HeadlessSite,
    markt: MarktSite,
  }
  const Site = siteId ? sites[siteId] : null
  if (!Site) return <div>Select a site</div>
  return <Site />
}

const meta: Meta<typeof SiteRenderer> = {
  title: 'Sites',
  component: SiteRenderer,
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component: `Auto-generated site stories from @mdxui/examples.\n\nThis includes ${siteRegistry.length} real domain landing pages using various @mdxui layouts.`,
      },
    },
  },
  tags: ['autodocs'],
}

export default meta
type Story = StoryObj<typeof SiteRenderer>

/** agentic.md - AI Agents in Markdown - Build powerful AI agents using only Markdown. */
export const Agentic: Story = {
  name: 'agentic.md',
  render: () => <AgenticSite />,
  parameters: {
    docs: {
      description: {
        story: 'AI Agents in Markdown - Build powerful AI agents using only Markdown. Uses DuskLayout.',
      },
    },
  },
}

/** agentic.md - With cyan-blue gradient instead of purple-blue */
export const AgenticCyanBlueGradient: Story = {
  name: 'agentic.md (CyanBlueGradient)',
  render: () => <DuskLayout {...agenticData} gradient="cyan-blue" />,
  parameters: {
    docs: {
      description: {
        story: 'With cyan-blue gradient instead of purple-blue',
      },
    },
  },
}

/** agentic.md - Without the glow effect */
export const AgenticWithoutGlow: Story = {
  name: 'agentic.md (WithoutGlow)',
  render: () => <DuskLayout {...agenticData} glow={false} />,
  parameters: {
    docs: {
      description: {
        story: 'Without the glow effect',
      },
    },
  },
}

/** advertis.ng - AI Advertising Platform - Ads that optimize themselves. */
export const Advertis: Story = {
  name: 'advertis.ng',
  render: () => <AdvertisSite />,
  parameters: {
    docs: {
      description: {
        story: 'AI Advertising Platform - Ads that optimize themselves. Uses DuskLayout.',
      },
    },
  },
}

/** advertis.ng - With purple-blue gradient instead of orange-red */
export const AdvertisPurpleBlueGradient: Story = {
  name: 'advertis.ng (PurpleBlueGradient)',
  render: () => <DuskLayout {...advertisData} gradient="purple-blue" />,
  parameters: {
    docs: {
      description: {
        story: 'With purple-blue gradient instead of orange-red',
      },
    },
  },
}

/** workflow.md - Workflows in Markdown - Automation that reads like documentation. */
export const Workflow: Story = {
  name: 'workflow.md',
  render: () => <WorkflowSite />,
  parameters: {
    docs: {
      description: {
        story: 'Workflows in Markdown - Automation that reads like documentation. Uses QuartzLayout.',
      },
    },
  },
}

/** scrape.md - Web Scraping for AI - Turn any webpage into clean Markdown. */
export const Scrape: Story = {
  name: 'scrape.md',
  render: () => <ScrapeSite />,
  parameters: {
    docs: {
      description: {
        story: 'Web Scraping for AI - Turn any webpage into clean Markdown. Uses MistLayout.',
      },
    },
  },
}

/** scrape.md - With warm color theme */
export const ScrapeWarmTheme: Story = {
  name: 'scrape.md (WarmTheme)',
  render: () => <MistLayout {...scrapeData} warmth="warm" />,
  parameters: {
    docs: {
      description: {
        story: 'With warm color theme',
      },
    },
  },
}

/** api.ht - HyperText API - Build APIs the way the web was meant to work. */
export const ApiHt: Story = {
  name: 'api.ht',
  render: () => <ApiHtSite />,
  parameters: {
    docs: {
      description: {
        story: 'HyperText API - Build APIs the way the web was meant to work. Uses ScalarLayout.',
      },
    },
  },
}

/** db.ht - HyperText Database - A database you can browse. Every record is a URL. */
export const DbHt: Story = {
  name: 'db.ht',
  render: () => <DbHtSite />,
  parameters: {
    docs: {
      description: {
        story: 'HyperText Database - A database you can browse. Every record is a URL. Uses SonicLayout.',
      },
    },
  },
}

/** headless.ly - Headless CMS - Content is code. Version-controlled content with AI superpowers. */
export const Headless: Story = {
  name: 'headless.ly',
  render: () => <HeadlessSite />,
  parameters: {
    docs: {
      description: {
        story: 'Headless CMS - Content is code. Version-controlled content with AI superpowers. Uses LumenLayout.',
      },
    },
  },
}

/** markt.ng - AI Marketing Services - Marketing automation that thinks for you. */
export const Markt: Story = {
  name: 'markt.ng',
  render: () => <MarktSite />,
  parameters: {
    docs: {
      description: {
        story: 'AI Marketing Services - Marketing automation that thinks for you. Uses ScalarLayout.',
      },
    },
  },
}

