/**
 * Theme Context Injection Script Generator
 *
 * Generates scripts that inject theme context into the document,
 * handling:
 * - System preference detection
 * - Stored user preference
 * - Theme switching with CSS variable sync
 * - Integration with @mdxui/css worker
 *
 * @example
 * ```html
 * <!-- Inline to prevent FOUC (Flash of Unstyled Content) -->
 * <script src="/theme?theme=auto"></script>
 *
 * <!-- Or inline the script -->
 * <script>...</script>
 * ```
 */

/**
 * Theme modes
 */
export type ThemeMode = 'light' | 'dark' | 'auto' | string

/**
 * Theme configuration
 */
export interface ThemeConfig {
  mode: ThemeMode
  storageKey?: string
  cssWorkerUrl?: string
  attribute?: string
  enableTransitions?: boolean
}

/**
 * Generate theme context injection script
 *
 * @param theme - Theme mode ('light', 'dark', 'auto', or custom)
 * @param config - Optional configuration
 * @returns JavaScript code as a string
 */
export function generateThemeScript(
  theme: ThemeMode = 'auto',
  config?: Partial<ThemeConfig>
): string {
  const {
    storageKey = 'mdxui-theme',
    cssWorkerUrl = '',
    attribute = 'class',
    enableTransitions = true,
  } = config || {}

  return `/**
 * Theme Context Injection
 * Mode: ${theme}
 * Generated by @mdxui/js Worker
 */

(function() {
  'use strict';

  const STORAGE_KEY = '${storageKey}';
  const CSS_WORKER_URL = '${cssWorkerUrl}';
  const THEME_ATTRIBUTE = '${attribute}';
  const ENABLE_TRANSITIONS = ${enableTransitions};

  /**
   * Get system theme preference
   */
  function getSystemTheme() {
    if (typeof window === 'undefined') return 'light';
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
  }

  /**
   * Get stored theme preference
   */
  function getStoredTheme() {
    try {
      return localStorage.getItem(STORAGE_KEY);
    } catch {
      return null;
    }
  }

  /**
   * Store theme preference
   */
  function setStoredTheme(theme) {
    try {
      localStorage.setItem(STORAGE_KEY, theme);
    } catch {
      // Ignore storage errors
    }
  }

  /**
   * Resolve theme based on mode
   */
  function resolveTheme(mode) {
    switch (mode) {
      case 'auto':
        return getSystemTheme();
      case 'light':
      case 'dark':
        return mode;
      default:
        // Custom theme name
        return mode;
    }
  }

  /**
   * Apply theme to document
   */
  function applyTheme(theme, skipTransition = false) {
    const root = document.documentElement;

    // Disable transitions during theme change to prevent flicker
    if (skipTransition || !ENABLE_TRANSITIONS) {
      root.style.transition = 'none';
    }

    // Apply theme based on attribute type
    if (THEME_ATTRIBUTE === 'class') {
      // Class-based theming (e.g., Tailwind)
      root.classList.remove('light', 'dark');
      root.classList.add(theme);
    } else if (THEME_ATTRIBUTE === 'data-theme') {
      // Data attribute theming
      root.setAttribute('data-theme', theme);
    } else {
      // Custom attribute
      root.setAttribute(THEME_ATTRIBUTE, theme);
    }

    // Set color-scheme meta tag for browser UI
    const colorScheme = theme === 'dark' ? 'dark' : 'light';
    let meta = document.querySelector('meta[name="color-scheme"]');
    if (!meta) {
      meta = document.createElement('meta');
      meta.name = 'color-scheme';
      document.head.appendChild(meta);
    }
    meta.content = colorScheme;

    // Re-enable transitions
    if (!skipTransition && ENABLE_TRANSITIONS) {
      // Use setTimeout to ensure the theme change is applied first
      setTimeout(() => {
        root.style.transition = '';
      }, 0);
    }

    // Dispatch event for other scripts to listen to
    window.dispatchEvent(new CustomEvent('themechange', {
      detail: { theme, mode: getCurrentMode() }
    }));
  }

  /**
   * Get current theme mode
   */
  function getCurrentMode() {
    return getStoredTheme() || '${theme}';
  }

  /**
   * Get current resolved theme
   */
  function getCurrentTheme() {
    return resolveTheme(getCurrentMode());
  }

  /**
   * Set theme mode
   */
  function setTheme(mode, skipTransition = false) {
    setStoredTheme(mode);
    const resolved = resolveTheme(mode);
    applyTheme(resolved, skipTransition);
  }

  /**
   * Toggle between light and dark
   */
  function toggleTheme() {
    const current = getCurrentTheme();
    const next = current === 'dark' ? 'light' : 'dark';
    setTheme(next);
  }

  /**
   * Initialize theme on page load
   */
  function initTheme() {
    const mode = getCurrentMode();
    const theme = resolveTheme(mode);

    // Apply immediately to prevent FOUC
    applyTheme(theme, true);

    // Listen for system theme changes if in auto mode
    if (mode === 'auto') {
      const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
      const handler = () => {
        if (getCurrentMode() === 'auto') {
          applyTheme(getSystemTheme());
        }
      };

      // Use addEventListener if available, otherwise addListener
      if (mediaQuery.addEventListener) {
        mediaQuery.addEventListener('change', handler);
      } else {
        mediaQuery.addListener(handler);
      }
    }

    // Sync with CSS worker if configured
    if (CSS_WORKER_URL) {
      syncWithCSSWorker(theme);
    }
  }

  /**
   * Sync theme with CSS worker
   */
  function syncWithCSSWorker(theme) {
    // Send theme preference to CSS worker for optimized stylesheet serving
    fetch(\`\${CSS_WORKER_URL}/theme\`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ theme }),
      // Fire and forget
      keepalive: true,
    }).catch(() => {
      // Ignore sync errors
    });
  }

  /**
   * Expose global theme API
   */
  window.__mdxui_theme = {
    get: getCurrentTheme,
    getMode: getCurrentMode,
    set: setTheme,
    toggle: toggleTheme,
    apply: applyTheme,
  };

  // Initialize immediately (before DOMContentLoaded to prevent FOUC)
  initTheme();

  console.log('[mdxui/js] Theme initialized:', getCurrentTheme());
})();
`
}

/**
 * Generate minimal inline theme script
 *
 * This is a smaller version for embedding directly in <head>
 * to prevent Flash of Unstyled Content (FOUC).
 *
 * @param theme - Theme mode
 * @returns Minified JavaScript code
 */
export function generateInlineThemeScript(theme: ThemeMode = 'auto'): string {
  // Ultra-minimal version for inline use (must execute before body renders)
  return `(function(){const k='mdxui-theme',s=()=>matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light',g=()=>{try{return localStorage.getItem(k)}catch{return null}},m=g()||'${theme}',t=m==='auto'?s():m,r=document.documentElement;r.classList.add(t);let e=document.querySelector('meta[name="color-scheme"]');if(!e){e=document.createElement('meta');e.name='color-scheme';document.head.appendChild(e)}e.content=t==='dark'?'dark':'light';window.__mdxui_theme={get:()=>t,set:(n)=>{try{localStorage.setItem(k,n)}catch{}const nt=n==='auto'?s():n;r.classList.remove('light','dark');r.classList.add(nt);e.content=nt==='dark'?'dark':'light'},toggle:()=>{const n=t==='dark'?'light':'dark';window.__mdxui_theme.set(n)}}})();`
}

/**
 * Generate theme toggle component snippet
 *
 * Generates a simple HTML + JS snippet for a theme toggle button
 * that works with the theme system.
 *
 * @returns HTML string
 */
export function generateThemeToggleSnippet(): string {
  return `<button
  id="theme-toggle"
  aria-label="Toggle theme"
  style="padding:0.5rem;border-radius:0.5rem;border:1px solid var(--border);background:var(--background);cursor:pointer;"
>
  <span id="theme-icon">🌙</span>
</button>
<script>
(function(){
  const btn=document.getElementById('theme-toggle');
  const icon=document.getElementById('theme-icon');
  const api=window.__mdxui_theme;
  if(!api||!btn||!icon)return;
  const update=()=>{icon.textContent=api.get()==='dark'?'☀️':'🌙'};
  btn.addEventListener('click',()=>{api.toggle();update()});
  update();
  window.addEventListener('themechange',update);
})();
</script>`
}

/**
 * Generate theme preload link
 *
 * Generates a <link rel="preload"> tag for the theme script
 * to improve loading performance.
 *
 * @param workerUrl - Base URL of the JS worker
 * @returns HTML string
 */
export function generateThemePreloadLink(workerUrl: string): string {
  return `<link rel="preload" href="${workerUrl}/theme" as="script" crossorigin="anonymous">`
}
