// Generated by @mdxe/fumadocs - DO NOT EDIT
import type { BaseLayoutProps } from 'fumadocs-ui/layouts/shared'


export function baseOptions(): BaseLayoutProps {
  return {
    nav: {
      title: '@mdxe',
    },
  }
}
