// Generated by @mdxe/fumadocs - DO NOT EDIT
import { docs } from '@/.source/server';
import { type InferPageType, loader } from 'fumadocs-core/source';

let icons: Record<string, any> = {};
try {
  const lucide = await import('lucide-react');
  icons = lucide.icons;
} catch {
  // lucide-react not available
}

export const source = loader({
  baseUrl: '/docs',
  source: docs.toFumadocsSource(),
  icon(iconName) {
    if (!iconName || !icons[iconName]) return undefined;
    const { createElement } = require('react');
    return createElement(icons[iconName]);
  },
});

export function getPageImage(page: InferPageType<typeof source>) {
  const segments = [...page.slugs, 'image.png'];
  return {
    segments,
    url: `/og/${segments.join('/')}`,
  };
}

export async function getLLMText(page: InferPageType<typeof source>) {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000';
  const processed = await page.data.getText('processed');
  return `# ${page.data.title}

URL: ${baseUrl}${page.url}
${page.data.description ? `\n> ${page.data.description}\n` : ''}
${processed}`;
}
